# Define the stages that will be used in this pipeline
stages:
  - build

# Define the job for the build stage
build_job:
  # Use the 'development' runner for this job
  tags:
    - development
  # Assign this job to the 'build' stage
  stage: build
  # Use the 'alpine:latest' Docker image to run this job
  image: alpine:latest

  # Define the script that will be run for this job
  script:
    # Install Python3, Doxygen, and pip3
    - apk add python3 doxygen py3-pip
    # Install the 'openai' Python package
    - pip3 install openai
    # Change the working directory to 'main'
    - cd main
    # Run 'main.py' with Python3
    - python3 main.py
